<?php
$menus['Exemples']=array(
	'SimpleTPL'=>Router::generate("simpletpl"),
	'Formulaire'=>Router::generate("formulaire"),
	'C.R.U.D'=>Router::generate("crud"),
	'Redirect'=>Router::generate("redirect"),
	'Download'=>Router::generate("download"),
	'Ajax'=>Router::generate("ajax")
	);
$menus['Test']=Router::generate("test");
?>
