<?php
$menus['Exemples']=array(
	'SimpleTPL'=>"?module=SimpleTemplate",
	'Formulaire'=>"?module=Formulaire",
	'C.R.U.D'=>"?module=CRUD",	
	'Redirect'=>"?module=Redirect",
	'Download'=>"?module=DownloadFile",
	'Ajax'=>"?module=Ajax"
	);
$menus['Test']="?module=TestMembre";
?>